#!/bin/zsh

# 読書ノートを作成するスクリプトです。

# コマンドの使い方
usage() {
  echo "\n使用法:\n $ note <title> <start> <end>"
}

# エラーハンドリング
errorHandling () {
  if [ ! $# = 4 ] || [[ $2 < 0 ]] || [[ $2 > $3 ]]
  then
    echo "不正な引数です。"
    usage
    exit 1
  elif [ -d $4 ]
  then
    local noteDir=$4
    echo "${noteDir}ディレクトリがすでに存在します。"
    exit 2
  fi
}

# 指定したパスに目次を作成
makeIndex() {
  local target=$1
  local title=$2
  local start=$3
  local end=$4

  local firstIndex
  if [[ $start = 0 ]]
  then
    firstIndex=0
  else
    firstIndex=1
  fi

  local template="# ${title}\n\n## 目次"
  local chapter
  for chapter in {${start}..${end}}
  do
    template="${template}\n\n${firstIndex}. [](${chapter}/README.md)"
  done
  echo $template >> "${target}/README.md"
}

# 引数に指定したパスに画像ディレクトリ images を作成する
makeImages() {
  local target=$1
  mkdir -p ${target}/i/{f,l,p,t}
}

# 指定したパスに章ごとのディレクトリの内容を作成
makeChapters() {
  local target=$1
  local start=$2
  local end=$3

  local chapter
  for chapter in {${start}..${end}}
  do
    local chapterDir="${target}/$chapter"

    mkdir $chapterDir
    echo "#\n\n[目次](../README.md)" >> "${chapterDir}/README.md"

    makeImages ${chapterDir}
  done
}

# 指定したパスにGitリポジトリを作成
makeGitRepos() {
  local target=$1
  local title=$2

  cd $target
  git init
  git add -A
  git commit -m "「${title}」の読書ノートを作成しました。"
}

# ｎoteディレクトリの中身を作成する
makeNote() {
  local title=$1
  local start=$(printf "%02d" $2)
  local end=$(printf "%02d" $3)
  local noteDir=$4

  # 作業用ディレクトリ
  mkdir -p $noteDir
  # 目次
  makeIndex $noteDir $title $start $end
  # images
  makeImages $noteDir
  # 章ディレクトリ
  makeChapters $noteDir $start $end

  # git
  makeGitRepos $noteDir $title
}

main () {
  # 作成するノートディレクトリの名前
  local NOTE_DIR=note
  ## エラーハンドリング
  errorHandling $@ $NOTE_DIR
  # noteディレクトリを作成
  makeNote $@ $NOTE_DIR
}

main $@
